capture:
  width: 648
  height: 686

preprocessing:
  remove_outside_petri:
    apply: True
    center: [324, 343]
    radius: [304, 323]

background_subtraction:
  history: 300
  varTreshold: 32
  NMixtures: 2

trackpy:
  locate:
    minmass: 100 # 40 # 100
    separation: 30 # 50 # 30
    percentile: 50 # 70 # 50
    topn: 5
    diameter: 11 # 9 # 11
  link:
    search_range: 25 # 25 # 17
    memory: 50

find_worm:
  min_points: 200

labels:
  small_radix: 7
  big_radix: 10